#include<iostream>
using namespace std;
//CREATING MACRO THERE IS NO NEED OF SEMICOLON ';'

//IT MEANS IF PI IS WRITTEN ANHYWHERE IN CODE THEN IT WILL GET REPLACED WITH 3.14 BEFORE COMPILATION TIME

/*BENEFIT IS THERE IS NO NEED TO EXTRA STORAGE AS THIS IS NOT A VARIABLE AND ALSO THERE IS NO NEED TO ALLOCATE MEMEORY.
 AS YOU ARE REPLACING IT BEFORE COMPILATION TIME AND ALSO IT IN NOT GOING TO CHANGE LIKE YOU CANNNOT UPDATE IT LATER INT THE CODE.
  */ 

 //MACRO IS A PICE OF CODE IN A PROGRAM THAT IS REPLACED BY A VALUE OF MACRO.IT MADE EASY FOR US TO MAINTAIN THE CODE.
#define PI 3.14


int main(){
   int  r=5;
	 
	 
	 double area=PI*r*r;
	 
	//PI=PI+1;  THIS IS USELESS HERE  
	 
	 cout<<area<<endl;
	 
	
	
}